use_frameworks!

target 'Reversi_Example' do
  pod 'Reversi', :path => '../'
  
  pod 'Firebase/RemoteConfig'
  pod 'OptimizelySDKiOS'
end

target 'Reversi_Tests' do 
  pod 'Reversi', :path => '../'
end
